### ISSUE TITLE
DSHttpAdapter default $http config

### ISSUE THREAD

**Issue by kenjiqq** [js-data/js-data-angular#111]
I think it would be good if you could provide some default config for $http in the DSHttpAdapter. 
So you can add stuff like interceptors if you want to handle certain errors etc, for example that the user is not authenticated with the api. 

I was thinking about these changes to the DSHttpAdapterProvider

``` javascript
    var defaults = this.defaults = {
        /**
         * @doc property
         * @id DSHttpAdapterProvider.properties:defaults.queryTransform
         * @name defaults.queryTransform
         * @description
         * Transform the angular-data query to something your server understands. You might just do this on the server instead.
         *
         * @param {string} resourceName The name of the resource.
         * @param {object} params Params sent through from `$http()`.
         * @returns {*} Returns `params` as-is.
         */
        queryTransform: function(resourceName, params) {
            return params;
        },
        httpConfig: {}
    };
```

``` javascript
function HTTP(config) {
    var start = new Date().getTime();

    config = DSUtils.deepMixIn(this.defaults.httpConfig, config);
    return $http(config).then(function(data) {
        $log.debug(data.config.method + ' request:' + data.config.url + ' Time taken: ' + (new Date().getTime() - start) + 'ms', arguments);
        return data;
    });
}
```

Then one could add config to all $http requests that angular-data executes

``` javascript
DSHttpAdapter.defaults.httpConfig = {
    interceptor: /* ... */
};
```

The reason for not just configuring $http globally would be if you wanted to do other $http requests to other sources that is not your API

**Comment by perrierism** [comment]
Sorry, can this be done or not? I see this was added in [0.10.5 (changelog) ](https://github.com/js-data/js-data-angular/blob/master/CHANGELOG.md#0105---14-august-2014) / ffae052

Then there is the previous comment saying there is actually no API to do this. I still see the code for this in the source, but neither  DSHttpAdapter(Provider?).defaults.httpConfig  *or*  $httpProvider.interceptors.push(...) seems to have any effect on js-data-angular calls.

**Comment by jmdobry** [comment]
> is there a way to make an interceptor which is specific to DS

No, not if you're going to use the http adapter that comes with js-data-angular (that's not how Angular's DI works).

However, you can load js-data-http which uses `axios` for http (instead of `$http`). You can add interceptors to axios via axios' api, which will not be used by `$http`.
