### ISSUE TITLE
Support for payload in DSHttpAdapter.DEL

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [js-data/js-data-angular#127]
The DSHttpAdapters delete request should probably have optional payload support as there are APIs which use this functionality such as [elasticsearch](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-delete-by-query.html). Better to add it sooner rather than later when breaking changes are more difficult to handle, as seen [here](http://goo.gl/hl2v4U).

**Comment by jayakrishnapulipati** [comment]
Thanks a lot it works out for me....:)
