### ISSUE TITLE
Custom endpoint URLs for specific filter/action

### ISSUE THREAD

**Issue by elado** [js-data/js-data-angular#168]
My endpoints are:

``` sh
/articles # all articles
/users/:id/articles # all articles by user
```

I want to use the same defined resource for both endpoints, but with a different filter.
I see that endpoints can't be changed after definition, even when sending a new one as an option.

``` js
Article.findAll() // /articles
Article.findAll({}, { endpoint: "/users/" + userId + "/articles" }) // /users/:id/articles
```

How about adding to `DSHttpAdapterProvider` http methods overriding option, exactly like `options.baseUrl || resourceConfig.baseUrl` but for `endpoint`?

``` js
DSUtils.makePath(
  options.baseUrl || resourceConfig.baseUrl, // exists
  options.endpoint || resourceConfig.endpoint // currently only resourceConfig.endpoint
)
```

**Comment by altschuler** [comment]
How is this done in v3?
