### ISSUE TITLE
Disabling caching for a resource

### ISSUE THREAD

**Issue by jintoppy** [js-data/js-data-angular#211]
I couldn't find it in another areas. Thats why putting it here. There is a "disabled" property in angular-cache. But, when defining a resource, is there any option to set caching as disabled?

**Comment by alexilyaev** [comment]
@jmdobry This comes up first in Google, but there's no link to a mailing list.
Could you write the answer here as well?

**Comment by jmdobry** [comment]
[Gitter channel](https://gitter.im/js-data/js-data)

[Mailing List](https://groups.io/org/groupsio/jsdata)

**Comment by isneezy** [comment]
Cant Find an answer for this :-1:
