### ISSUE TITLE
Syntax Highlighting for Docs

### ISSUE THREAD

**Issue by CWSpear** [js-data/js-data-angular#220]
Would it be possible to get syntax highlighting for the [docs](http://angular-data.pseudobry.com/documentation/guide/angular-data/index)?

**Comment by demisx** [comment]
When will js-data-angular be released roughly? I also find current documentation without syntax higjlighting painful to read. My eyes aren't that great.

**Comment by jmdobry** [comment]
js-data-angular is ready to go. It's only in beta for beta's sake. As soon as I release 1.0 I'll migrate the project and get it tagged in bower/npm. [js-data's docs](www.js-data.io) are much better.

I don't have the desire nor time to spend on the syntax highlighting. Luckily this is open source and can accept contributions...

**Comment by demisx** [comment]
I understand. Especially since js-data-angular replaces angular-data soon.

**Comment by jmdobry** [comment]
The [new docs](http://www.js-data.io) are a billion times better. I'm not going to expend any effort on syntax highlighting for the old docs.
