### ISSUE TITLE
Supporting methods on model instances

### ISSUE THREAD

**Issue by chadwithuhc** [js-data/js-data-angular#227]
I would like to see the same `save(), destroy(), etc.` on the returned item instances by default. Is there currently a reason why they aren't?

``` js
// Example code
ModelName.find(1).then(function (item) {
  item.destroy();
});
```

For the mean time I am adding them with `defineResource()`.

``` js
var Model = DS.defineResource({
    name: 'subjects',
    methods: {
      destroy: function () {
        return Model.destroy(this.id);
      }
    }
  });
```

**Comment by astrism** [comment]
Is it possible to add DSEject as well?

**Comment by jmdobry** [comment]
Sure
