### ISSUE TITLE
CSP unsafe-eval error

### ISSUE THREAD

**Issue by jamesspencer** [js-data/js-data-angular#242]
The use of `new Function()` and `eval()` prevents us from using angular-data due to Content Security Policy violations: https://developer.chrome.com/extensions/contentSecurityPolicy

Can/will this be changed?

Thanks!

**Comment by jmdobry** [comment]
js-data and js-data-angular (angular-data 2.0) have been updated to observe-js 0.5.4, so I believe this issue is fixed with js-data v1.0.0 + js-data-angular v2.0.0

**Comment by jamesspencer** [comment]
Success!

Thanks :)
