### ISSUE TITLE
Multiple belongsTo

### ISSUE THREAD

**Issue by kentcdodds** [js-data/js-data-angular#250]
I have a use case where a single resource can belong to multiple parents. Rather than defining a separate resource for each of these, I would prefer to simply have multiple `belongsTo` objects and angular-data managing the url based on the params and/or `localKey`.

**Comment by brentwalther** [comment]
Ping. I also have this use case. I have a `Post` model that has two subclasses (`Question` and `Answer) that each `haveMany` of the same model (`Comment`, in my case). Therefore, I need to be able to do something like the following:

```
relations: {
  belongsTo: {`
    answer: {
      parent:    true,
      localKey: 'post_id',
      endpoint: 'answers'
    },
    question: {
      parent:    true,
      localKey: 'post_id',
      endpoint: 'questions'
    }
  }
}
```

**Comment by jmdobry** [comment]
Please re-submit this issue to https://github.com/js-data/js-data/issues for discussion an implementation there.
