### ISSUE TITLE
Explore adding "actions", an easy way to add static resource methods

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data-angular#261]
See #252

**Comment by Tlvenn** [comment]
+1
Any chance to tackle this soon ?

**Comment by demisx** [comment]
+1 this would be awesome.

**Comment by kentcdodds** [comment]
I'll gist you my method for doing this. Perhaps it will be helpful.

**Comment by jmdobry** [comment]
That would be great

**Comment by kentcdodds** [comment]
Here you go. Let me know if you have any questions. https://gist.github.com/kentcdodds/6d4616b431a079808c6f

**Comment by jmdobry** [comment]
Initial implementation already complete in [js-data](https://github.com/js-data/js-data) + [js-data-angular](https://github.com/js-data/js-data-angular). Closing this in favor of the feature already being available there.
