### ISSUE TITLE
Allow dot fields in orderBy filter

### ISSUE THREAD

**Issue by mattlewis92** [js-data/js-data-angular#272]
Please can you allow dot notation in the orderBy of the filter. e.g. so you can specify:
{orderBy: [['name.last', 'ASC']]} 

It should just require the compare function changing in the default filter to use a function like this to obtain the values:
```javascript
var evalObjectProperty = function (obj, property) {
        var arr = property.split('.');
        if (obj) {
          while (arr.length) {
            if (obj) {
              obj = obj[arr.shift()];
            }
          }
        }
        return obj;
      }
```

Thank!

**Comment by jmdobry** [comment]
Please re-submit this issue to https://github.com/js-data/js-data/issues for discussion an implementation there.
