### ISSUE TITLE
DS.create not using correct endpoint when using relationships

### ISSUE THREAD

**Issue by rkingon** [js-data/js-data-angular#276]
Hey! Love the work on this plugin so far.

Have a small issue where if I use DS.create for a new resource, it's not using the correct endpoint for the relationship. However, if I inject first then use DS.save it does work properly.

Here are my "defineResource" calls

``` coffeescript
DS.defineResource
  name: 'annotations'
  relations:
    belongsTo:
      assignments:
        parent: true
        localField: "assignment"
        localKey: "user_assignment_id"

DS.defineResource
  name: 'assignments'
  endpoint: 'assignments'
  relations:
    hasMany:
      annotations:
        localField: 'annotations'
        foreignKey: 'user_assignment_id'
```

When I call the following to remove it, it works fine. The endpoint is:

``` coffeescript
# some scripting that leads me to haveing the variable id as an annotations id
DS.destroy 'annotations', id
# End point: /api/assignments/:user_assignment_id/annotations/:annotation_id
```

Create, however, does not work as expected:

``` coffeescript
# Some scripting that leads me to a new "annotation" object, bound to the variable: annotation
DS.create 'annotations', annotation
# End point: /api/annotations/:annotation_id
# Should be: /api/assignments/:user_assignment_id/annotations/:annotation_id
```

When injecting first, then saving... I do get the correct endpoint:

``` coffeescript
# Some scripting that leads me to a new "annotation" object, bound to the variable: annotation
DS.inject 'annotations', annotation
  linkInverse: true # Needed to update the assignment model
DS.save 'annotations', annotation.id
# End point: /api/assignments/:user_assignment_id/annotations/:annotation_id
```

While I can totally do that, I think the fact that create doesn't work properly is a bug so wanted to bring it to your attention. Will also be much cleaner of course to run create and have it inject the data when there is a valid response from the server.

Also, the "linkInverse" -- would that be available on "create" as well?

Thanks!

**Comment by benrich** [comment]
Out of interest.  Was this last comment actioned upon?  (if necessary).  Thanks,

**Comment by jmdobry** [comment]
Yes I did. The tests include a working example like the one you described, so you'll have to create a [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates your issue.
