### ISSUE TITLE
resource.filter for substring

### ISSUE THREAD

**Issue by stephen-murby** [js-data/js-data-angular#295]
```DEFAULT_RECORDS = [{
        id: 1,
        name: 'John Evans',
        number: '01928 356115'
    },{
        id: 16,
        name: 'Murbinator',
        number: '053180 080000'
    }];```

```
lookup: function (name) {
            var retrievedRecords = {};
            var _this = this;
            Record.findAll().then(function () {
                var params = {
                    where: {
                        name: {
                            'in': name
                        }
                    }
                };
                retrievedRecords = Record.filter(params);
                debugger;
                _this.lookupSuccess(retrievedRecords);
            }).catch(function (error) {
                console.log(error);
            });
        },
```

Where `'in': name` name is "John" no record is found
Where `'in': name` name is "John Evans" one record is found.
Looking at [issue 238](https://github.com/jmdobry/angular-data/issues/238) that appears to be the way I should be filtering but is not the value I expect to be return for sub-string filtering.

angular-data : 1.5.3
angular : 1.3.8

**Comment by jmdobry** [comment]
I misspoke in that issue. You're looking for the `contains` operator, which is available in 2.0 (js-data-angular).

**Comment by stephen-murby** [comment]
Thanks.

**Comment by jmdobry** [comment]
@stephen-murby Actually now that I take a closer look at the code, I'm not so sure the functionality you're looking for exists yet. Re-opening.

**Comment by jmdobry** [comment]
Please re-submit this issue to https://github.com/js-data/js-data/issues for discussion an implementation there.
