### ISSUE TITLE
Keep it DRY

### ISSUE THREAD

**Issue by sloosch** [js-data/js-data-angular#306]
Noticed that js-data-angular shares alot of the same code as js-data-http.
IMHO maintaining multiple projects with Copy&Paste Code will become rapidly a mess.
Some kind of abstract-http-adapter with interchangeable http-backend seems to be missing.

**Comment by jmdobry** [comment]
At this point in time, the amount of effort required to create another project and integrate it into the build of the two http adapters so as not to force developers to load another library is far greater than any http adapter changes coming in the foreseeable future. The API for $http and axios might very well diverge in the future, and I don't want to have http adapter adapters.

**Comment by jmdobry** [comment]
This has been implemented.
