### ISSUE TITLE
Export the module name

### ISSUE THREAD

**Issue by kentcdodds** [js-data/js-data-angular#308]
See [my post](https://medium.com/@kentcdodds/how-to-distribute-your-angularjs-module-e04d4dd58ddc) about it and [this angular.js PR comment](https://github.com/angular/angular.js/pull/10732#issuecomment-74986139) for reasons as to why it's a good idea. Basically, enables this:

```javascript
angular.module('myModule', [require('js-data-angular')]);
```

**Comment by kentcdodds** [comment]
With the angular team moving to this method, I've been able to move most of my dependencies to use this method. Would love to see js-data-angular join the ranks there :D

**Comment by jmdobry** [comment]
PR?

**Comment by kentcdodds** [comment]
Totally reasonable. One sec...
