### ISSUE TITLE
Webpack: the request of a dependency is an expression

### ISSUE THREAD

**Issue by kentcdodds** [js-data/js-data-angular#309]
When using webpack with js-data-angular, I get this warning:

> WARNING in ./~/js-data-angular/src/index.js
> Critical dependencies:
> 73:16-40 the request of a dependency is an expression
>  @ ./~/js-data-angular/src/index.js 73:16-40

This is because of [this line](https://github.com/js-data/js-data-angular/blob/138c7282698e7b4b8c3e1e928aa7f40e977c3d0e/src/index.js#L73) which requires adapters based on their name. I don't have a suggested fix for this warning. Webpack handles it in a bit of a hackish way. I would really love to not have to worry about this though. Would love to talk about what could be done to avoid the require expression statement.

**Comment by jmdobry** [comment]
js-data-angular requirements:

- Module exports the angular module name.
- Does _not_ attach anything to the window (it's an angular lib)
- Consumable in someone's browserify/webpack build (CommonJS compatibility).
- Consumable in someone's r.js build (AMD compatibility).
- Detect that js-data has been loaded and is available. Need to get a reference to the `JSData` object.
- Automatically create a `DS` angular service (instance of `JSData.DS`)
- Detect if any other js-data adapters have been loaded
- Automatically create the angular services for each available adapter

For detecting whether other js-data libs have been loaded, do I just need to make sure those libs attach something to the window, regardless of what module system was used to load them? Some of the js-data libs need to work in Node.js as well. I'm wondering if webpack is the right tool for some of this and I should switch?

**Comment by kentcdodds** [comment]
Well, as far as switching, I love webpack and recommend it. But I believe you're using browserify (am I right) and I understand that they are similar in a lot of ways (though I have a browserify-only bug right now in angular-formly that I'm not excited about).

I gave it about a half hour to try and refactor the js-data-angular adapter so that webpack could recognize the expression as a specific require request because I know that Webpack has the power to interpret code and what require statements might be. I was unsuccessful because I misunderstood the feature...

The feature is called [context](http://webpack.github.io/docs/context.html) and I think it's mostly used for local dependencies. I think that the [ContextReplacementPlugin](http://webpack.github.io/docs/list-of-plugins.html#contextreplacementplugin) could maybe be used to resolve this issue, but I'm not certain. If that is the case, then it's something that I'll have to do on my end and then we should add a how-to in the docs for future generations :-)

I'll take a look at it and let you know. Thanks.

**Comment by jonrh** [comment]
@kentcdodds Where you successful in using *ContextReplacementPlugin*?

**Comment by kentcdodds** [comment]
I think I may have been, but js-data has been updated to no longer have this problem. However, I should point out that I did have to do a few special things to avoid warnings/issues in development, test and prod. Here's an example:

```javascript
var path = require('path');
var dev = process.env.NODE_ENV === 'development';

module.exports = {
  // ... other stuff
  resolve: {
    // ... other stuff
    alias: {
      'js-data': dev ? undefined : here('node_modules/js-data/dist/js-data')
    }
  },
  externals: {
    'js-data-schema': 'FALSE'
  }
}

function here(p) {
  return path.join(__dirname, p || '');
}
```

And then in my app, I assign `window.FALSE = false`. It's not the best thing in the world, but it's a set it and forget it type thing.

Hope that helps!

**Comment by kentcdodds** [comment]
Note, the reason for the alias is because I don't want to use `js-data-debug` in production.

**Comment by jmdobry** [comment]
In js-data-angular 3.0 I've now got UMD fully figured out, but there's no getting around the warning printed about the dependencies as an expression if js-data-angular is to be capable of dynamically detecting that you've bundled various adapters and then registering instances of them with angular's dependency injector.

**Comment by jmdobry** [comment]
I created a directory called `build_examples` that show building an app that depends on js-data, js-data-angular.
