### ISSUE TITLE
DSHttpAdapter#find/create/update/destroy do not call queryTransform

### ISSUE THREAD

**Issue by jessemorton** [js-data/js-data-angular#313]
Per discussion at https://groups.io/org/groupsio/jsdata/thread/40098 it's expected that `DS#find` will run the (optionally) passed `params` object through `DSHttpAdapterProvider.defaults.queryTransform` like how `DS#findAll` does. Currently this does not happen.

**Comment by MikaAK** [comment]
I seem to still be having this problem. In my config block I've defined a` deserialize` and `transformQuery` function, but no console.log gets hit. Is there anything I'm missing? I'm on V2.2.2! If anyone knows what I can do that would be great!

```javascript
DSHttpAdapterProvider.defaults.deserialize = (resourceName, data) => {
    console.log(resourceName, data)
    return data ? ('data' in data ? data.data : data) : data;
}

DSHttpAdapterProvider.defaults.queryTransform = function(params) {
    console.log(params, 'transform')
   return params
}
```

**Comment by jmdobry** [comment]
The signature for `queryTransform` is actually `queryTransform(resource, params)` not `queryTransform(params)`. 

As you can see [here](https://github.com/js-data/js-data-angular/blob/05c4e7a2065bbb8fa04d30adf1a461829e6acbc7/dist/js-data-angular.js#L363) `queryTransform` is called in `DSHttpAdapter#find`. You'll find similar code in the other methods. 

Could you possibly create a jsfiddle, plunker or jsbin that demonstrates the issue? What version of js-data are you using? Are you using any other js-data libraries?

**Comment by MikaAK** [comment]
Ah I found the problem. queryTransform isn't called when you define extra default actions. I'll create a plunker.

**Comment by jmdobry** [comment]
Ah, that's because a generated action uses `DSHttpAdapter#GET` or `#POST`, which don't call `queryTransform`.

**Comment by MikaAK** [comment]
Wouldn't it be better if they did? Unless there's another way, new actions can't get transformed and also return a full structure instead of the data since deserialize is also not called.

**Comment by jmdobry** [comment]
I tend to agree, though at this point I'm not sure that if add `queryTransform` to those methods it wouldn't be a breaking change for some people.
