### ISSUE TITLE
Switch to using peerDependencies

### ISSUE THREAD

**Issue by kentcdodds** [js-data/js-data-angular#314]
This way I can have my own version of `angular` and `js-data` and I'm not loading angular into the browser twice. http://blog.nodejs.org/2013/02/07/peer-dependencies/

**Comment by jmdobry** [comment]
So:

```json
"peerDependencies": {
  "angular": ">=1.1.0",
  "js-data": ">=1.1.0"
}
```

?

**Comment by kentcdodds** [comment]
I believe that would work!

**Comment by jmdobry** [comment]
So I should probably do something like this in all of the adapters too?

**Comment by kentcdodds** [comment]
That would be nice. It allows me to use my own version of js-data and angular so I'm not loading different versions for different adapters.

**Comment by joshuabc** [comment]
Big +1 for this, it would be nice when using Browserify to avoid the "tried to load Angular twice" error.

**Comment by jmdobry** [comment]
This is fixed in 3.x (3.0.0-rc.1 is the latest pre-release at this point in time).
