### ISSUE TITLE
Bug in orderby when written different ways

### ISSUE THREAD

**Issue by tuurbo** [js-data/js-data-angular#315]
As far as i understand, both should return the same ordered result, but the bottom one does nothing.

Version: js-data 1.5.8  + js-data-angular 2.2.3

From Docs: http://www.js-data.io/v1.5.2/docs/query-syntax#sorting-sortorderby

**Works:**
```
Image.bindAll({
	orderBy: [
		['sort_order', 'DESC']
	]
}, $scope, 'images');
```

**Doesn't Work:**
```
Image.bindAll({
	orderBy: ['sort_order', 'DESC']	
}, $scope, 'images');
```

**Comment by jmdobry** [comment]
```js
Image.bindAll({
	orderBy: ['sort_order', 'DESC']	
}, $scope, 'images');
```
will be rewritten to
```js
Image.bindAll({
  orderBy: [
    ['sort_order', 'ASC'],
    ['DESC', 'ASC']
  ]	
}, $scope, 'images');
```

The shorthands only work when sorting in ascending order.

**Comment by tuurbo** [comment]
Thanks, looks like the docs need to be tweaked, because this is what it says.

```
// Sorts users by age in descending order
User.filter({
  orderBy: ['age', 'DESC']
});
```

http://www.js-data.io/v1.5.2/docs/query-syntax#sorting-sortorderby

**Comment by jmdobry** [comment]
Fixed thanks.
