### ISSUE TITLE
Angular logs error on 404 responses

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [js-data/js-data-angular#316]
When a resource responds with a 404, additional to the js-data log, angular logs:
```
[object Object]
angular.js:11655 (anonymous function)
```

[Here is a plunker](http://plnkr.co/edit/1hwI4H?p=preview)

**Comment by jmdobry** [comment]
What is the concern here?

**Comment by Patrik-Lundqvist** [comment]
Oh, I just thought is was weird that I always got an extra ugly looking log error from angular every time I got a 404. If its not a problem, just close this.

**Comment by jmdobry** [comment]
Yeah, I think angular just logs 4xx and 5xx $http errors no matter what.

**Comment by bensurman** [comment]
I think this should be reopened as a bug.

If you run 2 identical calls
```javascript
$http.get('http://localhost:8080/api/12')
    .then(function () {
        console.log('success');
    }, function () {
        console.log('error');
    });

Api.find('12')
    .then(function () {
        console.log('success');
    }, function () {
        console.log('error');
    });
```
Both of them do log the error
```
angular.js:9866 GET http://localhost:8080/api/12 400 (Bad Request)
```
But an exception at angular.js:11655 is only thrown by the adaptor.
