### ISSUE TITLE
Angular is injected twice when I include js-data-angular

### ISSUE THREAD

**Issue by jgoux** [js-data/js-data-angular#318]
Hello,
as I pointed out in https://github.com/js-data/js-data-angular/issues/317#issuecomment-83133074, when I require js-data-angular in my project, it includes angularJS twice : the version I use (1.4.0-beta.5) and the version js-data-angular use (1.3.14).
Maybe is it because the notation ">=1.1.0" (https://github.com/js-data/js-data-angular/blob/master/package.json#L53) doesn't target beta releases ?

**Comment by jmdobry** [comment]
This will be fixed by #314

**Comment by jgoux** [comment]
Nice, thanks a lot for your help. :+1:
