### ISSUE TITLE
bindOne and bindAll force you to bind something to the scope

### ISSUE THREAD

**Issue by stringbeans** [js-data/js-data-angular#320]
The signatures for bindOne and bindAll indicate that it requires you to specify a member of the scope to bind the data to. However, in certain cases you may not want to do that and instead you only need to perform some operation on the data. 

This is just an optimization but ideally we should not have to bind the data to something on the scope

**Comment by jmdobry** [comment]
You don't have to bind anything to the $scope. Just use (DS#get)[http://www.js-data.io/docs/dsget] or (DS#filter)[http://www.js-data.io/docs/dsfilter] to get data out of the store, which is what `bindOne` and `bindAll` do under the hood anyway.
