### ISSUE TITLE
creating methods throws exception

### ISSUE THREAD

**Issue by tflori** [js-data/js-data-angular#321]
Creating a method in defineResource throws an exception at this point:
https://github.com/js-data/js-data-angular/blob/master/dist/js-data-angular.js#L552
config.method.toUppercase does not exist and is not mentioned in http://www.js-data.io/v1.5.12/docs/custom-instance-behavior

are there other things to keep in mind?

**Comment by jmdobry** [comment]
The line you mentioned is in js-data-angular, and has nothing to do with defineResource (which is in js-data). So perhaps you could create a plunker that demonstrates the issue? I have never seen this problem before.

**Comment by tflori** [comment]
Sorry, was may fault. I wrote method instead methods.
