### ISSUE TITLE
Angular throws exception on 4xx errors

### ISSUE THREAD

**Issue by bensurman** [js-data/js-data-angular#324]
See #316.  I think this should be reopened.

If you compare these (12 is an invalid id)
```javascript
$http.get('http://localhost:8080/api/12')
    .then(function () {
        console.log('success');
    }, function () {
        console.log('error');
    });

Api.find('12')
    .then(function () {
        console.log('success');
    }, function () {
        console.log('error');
    });
```
Both of them also log this error to console
```
angular.js:9866 GET http://localhost:8080/api/12 400 (Bad Request)
```
But an exception at angular.js:11655 is only thrown by the adaptor.

**Comment by jmdobry** [comment]
So this issue is an issue to re-open another issue?

Can you describe exactly what resolution is desired?

Here's a plunker that runs your example code: http://plnkr.co/edit/UokC9c?p=preview

Do you have any insight into this stack trace?
![stack_trace](https://cloud.githubusercontent.com/assets/1213510/6908667/f97e2d6a-d6fb-11e4-9082-a7cd900dfcb1.png)

The exception is thrown inside Angular, and then handled inside Angular (it just logs it). I'm not sure what I can do about it.

**Comment by bensurman** [comment]
Yea sorry I was going to comment on the old issue but seeing as it's closed I wasn't sure if you would see it.

Desired behaviour imo would be the same as angular's default $http behaviour, eg just log an error to console when you get a 4xx response error.  Not throw an exception.  For me it's a problem as I display angular exceptions with toasts in my admin console, and frequently lookup invalid ids on my backend to see if they can be used... 

Unfortunately after spending a lot of time digging around in the angular code I can't see a way to avoid it, although I don't have much experience so I could be missing something.  It looks like it's an intended consequence of returning $q.reject from the adaptor:

```javascript
  function processQueue(state) {
    var fn, promise, pending;

    pending = state.pending;
    state.processScheduled = false;
    state.pending = undefined;

    for (var i = 0, ii = pending.length; i < ii; ++i) {
      promise = pending[i][0];
      fn = pending[i][state.status];
      try {
        if (isFunction(fn)) {
          // angular's $http rejected promise is handled here
          promise.resolve(fn(state.value));
        } else if (state.status === 1) {
          promise.resolve(state.value);
        } else {
          // angular-js-data's rejected promise is handled here
          promise.reject(state.value);
        }
      } catch (e) {
        promise.reject(e);
        // exception only gets thrown if using js-data
        exceptionHandler(e);
      }
    }
  }
```

**Comment by jmdobry** [comment]
```js
try {
  if (isFunction(fn)) {
    promise.resolve(fn(state.value));
  } else if (state.status === 1) {
    promise.resolve(state.value);
  } else {
    // if it's handled here, then why do we get to the catch statement?
    promise.reject(state.value);
  }
} catch (e) {
  // how did we get here? What was synchronously thrown that this try-catch could have caught?
  promise.reject(e);
  // exception only gets thrown if using js-data
  exceptionHandler(e);
}
```

**Comment by bensurman** [comment]
Ahh yea you're right there is more going on there.  After the `else`, it loops again and gets handled by the `if` with this function
```javascript
  function (err) {
    if (resource) {
     delete resource.pendingQueries[id];
    }
    throw err;
  }
```

**Comment by jmdobry** [comment]
`return DSUtils.Promise.reject(err);` instead of `throw err;` appears to fix it.

**Comment by jmdobry** [comment]
An issue like this actually belongs on the js-data repo, since it's not a problem with js-data-angular. Closing in favor of js-data/js-data#101
