### ISSUE TITLE
Computed fields do not trigger digest cycle

### ISSUE THREAD

**Issue by mightyguava** [js-data/js-data-angular#327]
Newly computed values are not reflected in the scope when they are updated. Try modifying the inputs on the Plunkr. The computed "fullName" is always a change behind. (I'm on Chrome 41 OSX 10.10)

http://plnkr.co/edit/SHJA4RPdn03mRbvGFwcy?p=preview

I expected this to just work, but I guess the behavior makes sense since it's hard for js-data to figure out which scopes depend on the computed value to trigger $digest cycles for. Is there a better way to do this? I was hoping I could replace some angular filters.

Btw, loving this library a lot.

**Comment by mightyguava** [comment]
Hmm... maybe js-data-angular can call `rootScope.$applyAsync()` after updates to computed fields?

**Comment by jmdobry** [comment]
Except `$applyAsync` wasn't added to Angular until 1.3.x. 

The fields are re-computed in response to a `$digest` cycle being called on the `$rootScope`, but apparently the changes aren't being batched within those `$digest` cycles. 

It seems like it could cause an infinite loop of I change it so `$digest` triggers computed property recomputation which triggers `$digest` cycles which triggers computed property recomputation which triggers etc. etc. etc.

**Comment by jmdobry** [comment]
I've been meaning to have Resources emit a "change" event when the observer code detects changes in an object. This would enable you to do something like:

```js
app.controller('UserCtrl', function ($scope, $routeParams, User) {
  // this gives you finer control over performance/when $digest loops happen
  // rather than js-data-angular nuking your whole app with a bunch of $rootScope.$apply calls
  User.on('change', $scope.$apply);

  this.user = User.get($routeParams.id);
});
```

**Comment by mightyguava** [comment]
I'd only trigger `$digest` if the computed property's result actually changed. If the `$digest` then causes a change in the computed property's result again, then I'd say that's an application bug, though js-data would definitely need to do something to break the loop and error. You could probably do so by checking whether after calling scope.$digest(), the dependencies of the computed values changed and keep a counter on how many times that happens? Does sound ugly though.

The `change` event does sound useful in general. For my use cases, I think I'd only care if computed fields changed. Will there be some sort of granularity to filter the results by? And, will it be possible to subscribe to the change event on the Resource level and as well on the resource instance level?

Also, it'd be nice if there was some config option that could enable calling `$applyAsync` by default on computed field changes, for Angular 1.3+ code.

**Comment by jmdobry** [comment]
Here's another problem, all the code for handling computed properties is in js-data, which is framework-agnostic and has no knowledge of Angular or `$digest` stuff.

This might help you:

In your plunker you have:

```js
.controller('FooController', function ($scope, DS) {
    $scope.user = DS.inject('user', {
      id: 1,
      firstName: 'Billy',
      lastName: 'Joe'
    });
    DS.bindOne('user', 1, $scope, 'user');
  });
```

Try changing it to:

```js
.controller('FooController', function ($scope, DS) {
    $scope.user = DS.inject('user', {
      id: 1,
      firstName: 'Billy',
      lastName: 'Joe'
    });
    DS.bindOne('user', 1, $scope, 'user', function () {
      $scope.user.DSCompute();
    });
  });
```

It's not the most obvious thing, but it works. In fact, I could probably have js-data-angular do this for you...that would solve this problem. :)

**Comment by mightyguava** [comment]
Awesome, that should work. Thanks!

I think it'd be nice to also have a way to proxy bindOne like:

```js
.controller('FooController', function ($scope, User) {
  User.find(1)
    .then(function (user) {
      myCtrl.complexModel.setUser(user);
      user.DSBind($scope);
    });
});
```

The example is kind of contrived yes. I'm just trying to show that a lot of the time the user won't be bound directly on `$scope`, but instead as a property of a much more complex working model. I think what I'm getting at sounds like making the `expr` optional.

Not an immediate need for it. I can ping back when it comes up. Still in the early stages of integrating js-data into our codebase.

**Comment by jmdobry** [comment]
If I understand your complex model question correctly, then this should already work for you:

```js
// let's say the controllerAs is "FooCtrl"
.controller('FooController', function ($scope, User) {
  User.find(1);

  // "expr" can contain "." operators
  User.bindOne(1, $scope, 'FooCtrl.complexModel.user');
});
```

**Comment by mightyguava** [comment]
Hmm... Yes that works. I think I mostly find it strange that `User` is putting a value on the `$scope` for me, instead of me putting it on the my model and then telling the `$scope` to bind it.

**Comment by mightyguava** [comment]
Not a big deal. I'm happy with closing this out since the main issue has been resolved.
