### ISSUE TITLE
js-data-angular and cordova

### ISSUE THREAD

**Issue by ibewugb** [js-data/js-data-angular#330]
Hi, I have a problem using js-data-angular on my iPhone with cordova. When I just normally run it via my browser, its all fine. In cordova I get the message:

[Error] FAILED: Wed, 22 Apr 2015 16:43:56 GMT - GET foo - 0 410ms Object
	error (js-data-angular.js, line 384)
	logResponse (js-data-angular.js, line 581)
	processQueue (ionic.bundle.js, line 21825)
	(anonyme Funktion) (ionic.bundle.js, line 21841)
	$eval (ionic.bundle.js, line 23037)
	$digest (ionic.bundle.js, line 22853)
	$apply (ionic.bundle.js, line 23142)
	done (ionic.bundle.js, line 18295)
	completeRequest (ionic.bundle.js, line 18485)
	requestError (ionic.bundle.js, line 18436)
[Error] Failed to load resource: file:///private/var/mobile/Containers/Bundle/Application/[...].app/www/foo
The requested URL was not found on this server. (foo, line 0)

**Comment by jmdobry** [comment]
> `[Error] Failed to load resource: file:///private/var/mobile/Containers/Bundle/Application/[...].app/www/foo`

Looks like you've got an xhr request that's failing
