### ISSUE TITLE
Unit testing issue with mock $httpBackend

### ISSUE THREAD

**Issue by stevehipwell** [js-data/js-data-angular#334]
Is there a reason why unit testing with the mock $httpBackend wouldn't work?

**Comment by jmdobry** [comment]
Given the level of detail provided in this issue, I cannot think of any reasons.

**Comment by stevehipwell** [comment]
I have a working js-data-angular solution, but when I try to unit test it using angular-mocks and the mock $httpBackend I can't get it to work. The URL isn't being called and I get an error when trying to flush the $httpBackend (as there are no pending requests) or a time out if I comment out the flush line.

Is there any example code of unit testing js-data-angular this way?

**Comment by jmdobry** [comment]
Here's an example: https://github.com/js-data/js-data-angular/blob/master/test/datastore/async_methods/findAll.test.js

**Comment by jmdobry** [comment]
Closing since the js-data-angular tests are full of examples of how to test using $httpBackend.
