### ISSUE TITLE
Best way to flush the entire store (eject all data from all resources)

### ISSUE THREAD

**Issue by n9986** [js-data/js-data-angular#339]
`ejectAll` performs an eject on all data but it has to be performed on a particular resource. How do I unconditionally flush or remove all data from the store? A scenario where I would like to do this is on user logout. 

One way might be to delete the store object itself and create a new store from scratch. A js-data-angular specific suggestion would be really nice. Does this make sense as a js-data 2.0 feature?

**Comment by cah-danielmullins** [comment]
```js
function evacuateDataStore() {
          var registeredModels = _.keys(DS.definitions);

          angular.forEach(registeredModels, function(modelName) {
            DS.ejectAll(modelName);
          });
        }
```
I put this as a hook in my app's logout.

**Comment by n9986** [comment]
@cah-danielmullins That works too! I would be using this for now, but I guess it still might be worth considering `DS.evacuate()` or something like that. Thanks.

**Comment by jmdobry** [comment]
https://github.com/js-data/js-data/releases/tag/2.1.0

**Comment by jmdobry** [comment]
##### 2.1.0 - 07 July 2015

###### Backwards compatible API changes
- Added `DS#clear()`, which is a method only available on a store, and will call `ejectAll` on all of the store's resources
