### ISSUE TITLE
Random Bindalls

### ISSUE THREAD

**Issue by farid00** [js-data/js-data-angular#342]
Bindall and Bindonce seem to get called randomly and on unrelated changes.  In example plunkr http://plnkr.co/edit/wveT2J?p=preview, Bindall and Bindonce counters will go up without any user interaction over time, when just a user is added the agency bindonce counter goes up.  This is true for the reverse as well. It seems to be somewhat but not completely linked to the computed fields changing the lastmodified timestamp on the collections they run against, is this correct behavior?

**Comment by jmdobry** [comment]
It's because they're tied into the Angular app's $rootScope $digest loop.

**Comment by farid00** [comment]
Okay is there some reason it isn't stabilizing though? Without any interaction angular should stabilize after 1 or 2 digests.  However it may have been me browsing through tabs that fired it off more than once.  My bigger question is why does add agency increase the bindall count on users? They haven't been altered in anyway, does the filter call for computed fire this off?  

When I was checking the last modified times in the browser it seems to be constantly being modified.

**Comment by jmdobry** [comment]
The users bindOne and bindAll fire because the "agencies" computed property on the users changes when you add a new agency.

**Comment by farid00** [comment]
got it thank you
