### ISSUE TITLE
BindOne recomputing computed properties

### ISSUE THREAD

**Issue by kenborge** [js-data/js-data-angular#347]
Hi. We're in the process of upgrading to JSdata2. And we noticed that in the bindOne function you are recomputing computed properties but this is not happening in the bindAll function. So it seems to me that either it is required to recompute them and the bindAll function is wrong, or the bindOne function is running unneccery code. 
```javascript
let item = _this.get(resourceName, id)
if (item) {
  _this.compute(resourceName, id)
}
```

**Comment by jmdobry** [comment]
Probably needs to be added to `bindAll`.
