### ISSUE TITLE
How to use DSLocalForageAdapter

### ISSUE THREAD

**Issue by Harper04** [js-data/js-data-angular#348]
How can i use DSLocalForageAdapter with js-data-angular?

If i try to use as shown here http://www.js-data.io/docs/js-data-angular i get this:

Uncaught Error: [$injector:unpr] Unknown provider: DSLocalForageAdapterProvider <- DSLocalForageAdapterAdapter

After reading the code js-data-angular seems to only support DSHttpAdapter despite what the documentation is saying.

**Comment by jmdobry** [comment]
Since you provided no context (versions, example code, etc.) with which I could help you debug, I'm going to ask that you fork this plunker and use it to reproduce the issue you're seeing: http://plnkr.co/edit/XXlEKD?p=preview

**Comment by Harper04** [comment]
Hi,

turns out i was using the exact same Versions you do. So i looked deeper and debugged what was happening during the provider registration.

I used something like this which didn't work (using browserify with babel etc.):
```javascript
import angular from 'angular';
import 'js-data';
import 'js-data-localforage';
import 'js-data-angular';

window.app = angular.module('app', ['js-data']);
angular.module('app').config(['DSLocalForageAdapterProvider', function(DSLocalForageAdapterProvider){
}])
```
The import 'js-data-localforage' statement does not load the adapter in a way that js-data-angular can find it. Maybe it was foolish to think that these import statement are supported with browserify. I am new to this Webstuff

I solved it doing this:
```javascript
window["DSLocalForageAdapter"] = require('js-data-localforage');
require('js-data-angular');
```

**Comment by jmdobry** [comment]
You could also do something like this:

```js
...
import DSLocalForageAdapter from 'js-data-localforage'
import jsDataModuleName from 'js-data-angular'

angular.module('app', [jsDataModuleName])
.provider('DSLocalForageAdapter', function () {
  this.defaults = {}
  this.$get = () => new DSLocalForageAdapter(this.defaults)
})
```

**Comment by Harper04** [comment]
Thank you for that insight. Works for me too and is cleaner.
