### ISSUE TITLE
js-data-angular requesting axios

### ISSUE THREAD

**Issue by eestein** [js-data/js-data-angular#350]
When trying to load js-data-angular it requests for axios:

![image](https://cloud.githubusercontent.com/assets/2049255/13271083/639c52e8-da71-11e5-8433-46300f7868de.png)

Any idea why this is happening since it's only a `devDependencies`?

I'm using JSPM with SystemJS.
This is my config.js:

```
  "js-data": "npm:js-data@2.9.0",
  "js-data-angular": "npm:js-data-angular@3.1.0",
  "js-data-http": "npm:js-data-http@2.2.0",
```

```
  "npm:js-data-angular@3.1.0": {
      "angular": "npm:angular@1.5.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "js-data": "npm:js-data@2.9.0",
      "js-data-http": "npm:js-data-http@2.2.0"
    },
    "npm:js-data-http@2.2.0": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "js-data": "npm:js-data@2.9.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:js-data@2.9.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
```
@jmdobry

**Comment by jmdobry** [comment]
If you're using js-data-angular, then you shouldn't need to be loading js-data-http at all. But if you do want to be loading js-data-http, I believe you need something like:

```
meta: {
  'axios': { build: false }
}
```

or 

```
map: { axios: '@empty' }
```

I'm not sure which.

**Comment by eestein** [comment]
Thanks for your reply. I don't need it. It comes as a dep as you could see
from my config.js. I'm just installing it through jspm.

Is there any more information I can give you to help with the issue?

Thanks!

On Tuesday, 23 February 2016, Jason Dobry <notifications@github.com> wrote:

> If you're using js-data-angular, then you shouldn't need to be loading
> js-data-http at all. But if you do want to be loading js-data-http, I
> believe you need something like:
>
> meta: {
>   'axios': { build: false }
> }
>
> or
>
> map: { axios: '@empty' }
>
> I'm not sure which.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/js-data/js-data-angular/issues/350#issuecomment-187992139>
> .
>


-- 
Eros Eduardo Stein
m +55 27 98182 8770
Microsoft Certified Professional ID:9878485

**Comment by jmdobry** [comment]
You just need to tell JSPM/SystemJS to exclude `axios` from your build.

**Comment by eestein** [comment]
Ok, I'm gonna try that.

Thanks!

**Comment by eestein** [comment]
To solve it I had to use:

`map: { axios: '@empty' }`

like @jmdobry said, but also:

```
  'js-data-angular': {
    'format': 'global',
      'deps': [
        'angular',
        'js-data'
      ]
  }
```

**Comment by EvAlex** [comment]
I've installed it with
```
$ npm i --save-dev js-data js-data-angular
```

Then I required them in my code
```
import "js-data";
import "js-data-angular";
```

And I got error, because `axios` module is missing. The error went away after I installed it:
```
$ npm i --save-dev axios
```

I would recommend that you at least mention this dependency in README.md.

**Comment by jmdobry** [comment]
You should _not_ have to install axios, you should only have to configure your module bundler to ignore axios. Here are five examples that do just that: https://github.com/js-data/js-data-angular/tree/master/build_examples
