### ISSUE TITLE
DS.defineResource is not a function

### ISSUE THREAD

**Issue by randallmeeker** [js-data/js-data-angular#360]
Using angular 1.5, js-data 2.9 and js-data-angular 3.2.1

I have attempted installs via NPM and Bower and download directly from GIT.

Using the examples given 

```
angular.module('myApp')
  .run(function (DS) {
    DS.defineResource('user');
  })
```

I get the error `DS.defineResource is not a function.`

DS is defined and accessible.

**Comment by randallmeeker** [comment]
Also, attempted a plnkr, but can't get it working on there as well. An error occurs just loading the script. `Uncaught TypeError: Cannot read property 'deepMixIn' of undefined`. If I ignore that and continue to add `js-data` to angular, the whole thing goes boom (technical I know).

http://plnkr.co/edit/7ykzLZmjsP8jqgDAqEuJ?p=preview

**Comment by jmdobry** [comment]
So, your plunker is loading js-data v3 beta. Switch to 2.8.2 and your plunker will work.

**Comment by randallmeeker** [comment]
Thanks. I updated the plnkr and confirmed my mistake. 

Locally still not getting desired result. Going to attempt the setup that plnkr as close to my environment as I can with all the angular components and external libraries I'm using locally. 

I appreciate any more suggestions of how `DS` could be defined but `defineResource()` missing? , but will close this issue and will re-open if I discover anything new.

**Comment by randallmeeker** [comment]
Just so we're clear `defineResourse` is not a function, but `defineResource` is. Stupid misspelling !!!!!!!!

My bad for opening an issue.

**Comment by jmdobry** [comment]
Ahaha, oops.
