### ISSUE TITLE
Cannot add params to Nested resources 

### ISSUE THREAD

**Issue by jahead** [js-data/js-data-angular#361]
Hey for some reason my query parameters are being eroded ~~array~~ away* when used with nested resources. 
``` JS
    return DS.defineResource({
        name: 'measurement',
        relations: {
            // belongsTo uses "localField" and "localKey"
            belongsTo: {
                identity: {
                    // localField is for linking relations
                    // user.organization -> organization of the user
                    localField: 'user',
                    // localKey is the "join" field
                    // the name of the field on a measurement that points to its parent user
                    localKey: 'userId',
                    parent: true
                }
            }
        }
    });
```

The relations are working, 
so I can get it to call 
```
identity/{id}/measurement"
```

If however when I add params, like startdate and enddate, they don't show up on query String. 
If I don't use relations,, an object that doesn't have a parent then this works fine. 

I did some digging and the params are carried all way with the options object through to line 477 and then after (complied js) 
```
DSUtils.makePath(_this2.getEndpoint(parentDef, parentId, DSUtils._(parentDef, _options)), parentId, endpoint);
```
The params are lost. Is this expected behaviour? I've tried to use useFilter and other options flags. 

# EDIT 

I can get it to work with this
``` JS
DS.findAll('measurement',
{
    'startDate': "",
    'endDate': ""
  },
  {
    params: {
    userId: ""
  }
}
).then(success, error);
```

But not with using it like with the same inputs. 
``` JS
MeasurementStore.findAll()
```

**Comment by jmdobry** [comment]
Do either of these work?

```js
// GET /identity/1234/measurement
DS.findAll('measurement', {
  startDate: '',
  endDate: '',
  userId: 1234
})
```

```js
// GET /identity/1234/measurement
DS.findAll('measurement', {
  startDate: '',
  endDate: ''
}, {
  params: {
    userId: 1234
  }
})
```

**Comment by jahead** [comment]
Okay, so not to self, don't do dev late at night, 
This was a server problem on our end. 

Though I was getting false flags through js-data-http, the error message below erodes the query params off the string, and my logging in the js-data-angular also had supported it. But sorry about that. 

Now I know this, I will look to chrome network tab instead. But is there any improve that error message, it's quite misleading, at least for people new to the library. 
```
http://localhost:3541/api/v2/identity/9b2b871d-10cc-4ad0-98a3-95bc15192806/measurement - 404 44048ms
```

any who, you can close this now, sorry for the inconvenience, let me know if there anything I can do to help this project out.
